# Generated by Django 3.0.4 on 2020-04-01 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='alex', max_length=32),
            preserve_default=False,
        ),
    ]
